// <auto-generated />
using System;
using DGII.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DGII.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260213091935_FinalCleanup")]
    partial class FinalCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DGII.Domain.Entities.TaxReceipt", b =>
                {
                    b.Property<string>("NCF")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("TEXT");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NCF");

                    b.HasIndex("RncCedula");

                    b.ToTable("TaxReceipt");

                    b.HasData(
                        new
                        {
                            NCF = "E310000000001",
                            Amount = 200.00m,
                            Itbis18 = 36.00m,
                            RncCedula = "98754321012"
                        },
                        new
                        {
                            NCF = "E310000000002",
                            Amount = 1000.00m,
                            Itbis18 = 180.00m,
                            RncCedula = "98754321012"
                        });
                });

            modelBuilder.Entity("DGII.Domain.Entities.Taxpayer", b =>
                {
                    b.Property<string>("RncCedula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("RncCedula");

                    b.ToTable("Taxpayers");

                    b.HasData(
                        new
                        {
                            RncCedula = "98754321012",
                            CreationDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "JUAN PEREZ",
                            Status = 1,
                            Type = 1,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RncCedula = "123456789",
                            CreationDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "FARMACIA TU SALUD",
                            Status = 2,
                            Type = 2,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DGII.Domain.Entities.TaxReceipt", b =>
                {
                    b.HasOne("DGII.Domain.Entities.Taxpayer", "Taxpayer")
                        .WithMany("TaxReceipts")
                        .HasForeignKey("RncCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxpayer");
                });

            modelBuilder.Entity("DGII.Domain.Entities.Taxpayer", b =>
                {
                    b.Navigation("TaxReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
